#!/bin/bash

# Executes the main entry point from target
# location.

set -eu

SERVER_VERSION=1.18.2
SOURCE_DIR=$(pwd)
EXECUTABLE=$SOURCE_DIR/build/bin/mserver

cd $SOURCE_DIR/server && $EXECUTABLE $SERVER_VERSION
